# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'UniversalPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 消除警告
  inhibit_all_warnings!

  # Pods for UniversalPlayer
  pod 'StreamingKit'

end
